### PR TITLE
support for more http methods

### PR DESCRIPTION
**Pull request by Ma27**
the following http methods are missing in your implementation:

- LOCK/UNLOCK: http://www.webdav.org/specs/rfc2518.html#METHOD_LOCK
- LINK/UNLINK: http://tools.ietf.org/id/draft-snell-link-method-01.html
- PATCH: http://restcookbook.com/HTTP%20Methods/patch/

### CODE REVIEW

**Comment by Ma27** [comment]
ping @fdaciuk

**Comment by Ma27** [comment]
btw a new release would for that would be nice ;)

**Comment by fdaciuk** [comment]
Thanks @Ma27! But we need to find better ways to do that xD
The code will get very large :(

**Comment by Ma27** [comment]
thanks for your response.
What about making the XHRConnection public? The thing is that your library doesn't support a lot of http methods...

**Comment by fdaciuk** [comment]
> What about making the XHRConnection public?

I don't think so. I was thinking to change this one to accept any method, passing as string.
I don't know how yet, but I will keep opened this PR to think about it.

**Comment by luanmuniz** [comment]
A generic method is a good idea. Something like `ajax.call('GET', 'url', {...});`

**Comment by Ma27** [comment]
why?! Except naming stuff it doesn't make any difference...

**Comment by fdaciuk** [comment]
@luanmuniz that is the way :)
I thought in something like this for next release:

```js
ajax({
  method: 'get',
  data: {},
  url: 'http://blabla.com',
  // another configurations
})
.then()
.catch();
```

Using Promises/A+ interface, and preserving the `get`, `post`, `put` and `delete`  methods.

**Comment by fdaciuk** [comment]
@Ma27 done =)

**Pull request closed without merging**
