### PR TITLE
Added middleware option

### PR DESCRIPTION
**Pull request by terwanerik**
Added another option for middleware, e.g. after successfully doing a request, pass the response through a function that returns true or false. If true is given, the request is completed as usual, if false is given, the request will fail.

(using this to check if my user is still authenticated with each request)

### CODE REVIEW

**Comment by fdaciuk** [comment]
Hi @terwanerik! Thanks for sugggestion!

But I don't know if it makes sense, because even after `middleware` function returns `false`, the `error` method will be executed with the same `success` method response.

I think that should be implemented inside your project.

**Comment by terwanerik** [comment]
Why wouldn't that make sense? If the middleware fails, the catch block is called either way right?

With this middleware;
```
function middleware(response) {
  if (response.code == 403) {
    // user is not authenticated
    user.logout()
    return false
  }
  
  return true
}
```

And this call;
```
ajax.post('user/update').then((response) => {
  // show success message
}).catch(() => {
  // show error message
})
```

Everything would work as expected right? If the API responded that the user is not authenticated, the user is logged out.

It's alright if you don't implement it, just needed this for myself, and cared to share.

**Comment by fdaciuk** [comment]
Hey @terwanerik! Please, don't misunderstand me. My point is: I think this feature does not make sense **inside** the lib. But in your project, you can use composition, doing something like:

```js
function middleware (request) {
  return new Promise((resolve, reject) => {
    request.then((response) => resolve(response)).catch(() => {
      user.logout()
      reject()
    })
  })
}

function makePost (url, data) {
  return middleware(ajax.post(url, data))
}

makePost('user/update').then((response) => {
  // show success message
}).catch(() => {
  // show error message
})
```

What do you think? =)

**Comment by englishextra** [comment]
@fdaciuk I really hoped that native promise would have been built into the lib. Because I cannot see a way to catch errors, using api offered by the lib. Apart from building a wrapper myself, of course.

**Comment by fdaciuk** [comment]
@englishextra for now, you can use `async/await` :)

**Pull request closed without merging**
